### ISSUE TITLE
Callsign Switch

### ISSUE THREAD

**Issue by bhhoyer** [mcdermj/buster#31]
An attorney would call this 3rd party but I wanted to capture it.

During D-STAR net tonight on REF029 B linked to N7JNGateway, Peter and Dave reported that my Callsign switched from K7UDR to N6**\* Jeremy.

Not enough to do anything about

**Comment by mcdermj** [comment]
I think this may have resolved itself.  I haven't heard any complaints about my callsign showing up randomly, so I'm thinking this may have just been a beta problem.  Closing for now.
