### ISSUE TITLE
Com Port Not Found

### ISSUE THREAD

**Issue by TimKG8OC** [mcdermj/buster#51]
Hi, I just installed Buster, and it keeps telling me it can't find the vocoder. If I look in the preferences, it shows the info including the serial number of the ThumbDV which makes me think it can read that data anyway. In the system preferences it also shows the com port with the vocoder serial number listed. Can anybody tell me what I'm doing wrong? I have a 2017 iMac running 10.13.4

**Comment by TimKG8OC** [comment]
I tried to change it same issue.

<img width="500" alt="screen shot 2018-05-03 at 5 25 05 pm" src="https://user-images.githubusercontent.com/38962794/39603615-16f268cc-4ef7-11e8-8763-2ddbe96217ee.png">

**Comment by bhhoyer** [comment]
When did you purchase it?

**Comment by TimKG8OC** [comment]
About a year ago

**Comment by bhhoyer** [comment]
OK then it’s 460k8

Was it working with some other software and then you tried Buster?

**Comment by TimKG8OC** [comment]
This is the first time I have tried to use it. We purchased a new house and been busy moving, etc. I'm just now getting back into my ham stuff. I purchased the ThumbDV then just put it away until now.

**Comment by bhhoyer** [comment]
OK

Send it to:
NW Digital Radio
245 Highlands Drive
Friday harbor WA 98250

And I’ll check it out

Bryan K7UDR

**Comment by TimKG8OC** [comment]
Would it be better to bring it to Dayton and have you look at it? I'll there in a couple weeks for the Hamvention.

**Comment by bhhoyer** [comment]
Sure that works

**Comment by TimKG8OC** [comment]
Great! I'll bring it with me to Dayton. Thanks Bryan. 73 I'll also be at the D-Star meet and greet at the pizza place! Take care my friend.

**Comment by TimKG8OC** [comment]
Wow! I pulled it out, and put it back in one more time just for the heck of it, and it started working! Listening to REF030-C right now! I guess it's ok. Thanks for your help Bryan.

**Comment by bhhoyer** [comment]
Always insert it before you start Buster

**Comment by TimKG8OC** [comment]
ok, thanks
